# .github/workflows/deploy.yml
name: Deploy React site to GitHub Pages

on:
  workflow_dispatch:          # ↖ makes the “Run workflow” button appear
  push:                       # optional – keep or remove
    branches: [ main ]

permissions:
  contents: write             # lets the built-in GITHUB_TOKEN push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Tell git who is committing
        run: |
          git config --global user.name  "github-actions-bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
      
      - name: Build & publish
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

